name: Hello Workflow

on: workflow_dispatch

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World!"
      - name: Multiline shell commands
        run: |
          echo "First command"
          echo "Second command"
      - name: Say goodbye
        run: echo "Goodbye!"
      
